fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: api
    user_class: AppBundle\Entity\User

fos_rest:
    #disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    body_converter: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    format_listener:
        enabled: true
        rules:
            - { path: ^/, priorities: [ html, json, '*/*'], fallback_format: html, prefer_extension: true }

#    service:
#        serializer: jms_serializer.serializer

#    view:
#        view_response_listener: force
#        formats:
#            json: true
#            html: true
#        templating_formats:
#            html: true
#        force_redirects:
#            html: true
#        failed_validation: HTTP_BAD_REQUEST
#        default_engine: twig

    exception:
#        enabled: true
#        exception_controller: 'AppBundle\Controller\ErrorController::showAction'
#        codes:
#            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': 400
#            'Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException': 401
#            'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': 403
#            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
#            'Symfony\Component\HttpKernel\Exception\ConflictHttpException': 409
#            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
#        messages:
#            'Symfony\Component\HttpKernel\Exception\BadRequestHttpException': true
#            'Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException': true
#            'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException': true
#            'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': true
#            'Symfony\Component\HttpKernel\Exception\ConflictHttpException': true