all_battlemechs:
    path: /all
    defaults: { _controller: AppBundle:BattleMech:all }
    methods: [GET]
    requirements: { offset: \d+, limit: \d+, direction: \w+ }

all_battlemechs_in_weight_class:
    path: /weightClass
    defaults: { _controller: AppBundle:BattleMech:byWeightClass }
    methods: [GET]
    requirements: { offset: \d+, limit: \d+, weightClass: \w+, direction: \w+ }

all_battlemechs_name_like:
    path: /nameSearch
    defaults: { _controller: AppBundle:BattleMech:byName }
    methods: [GET]
    requirements: { offset: \d+, limit: \d+, name: \w+ }

get_battlemech:
    path: /{id}
    defaults: { _controller: AppBundle:BattleMech:get }
    methods: [GET]
    requirements: { id: \d+ }

add_battlemech:
    path: /
    defaults: { _controller: AppBundle:BattleMech:post }
    methods: [POST]

edit_battlemech:
    path: /{id}
    defaults: { _controller: AppBundle:BattleMech:put }
    methods: [PUT]
    requirements: { id: /d+ }

delete_battlemech:
    path: /{id}
    defaults: { _controller: AppBundle:BattleMech:delete }
    methods: [DELETE]
    requirements: { id: /d+ }