get_token:
    path: /getToken
    defaults: { _controller: AppBundle:Token:getToken }
    methods:  [POST]

register:
    path: /register
    defaults: { _controller: UserBundle:Registration:register }
    methods: [POST]

AppBundleProfile:
    prefix: /profile
    resource: "@AppBundle/Resources/config/routing/profile.yml"